package wasi-sandboxed:io@0.2.3;

interface stdio {
  write-stdout: func(contents: list<u8>);
  flush-stdout: func();

  write-stderr: func(contents: list<u8>);
  flush-stderr: func();
}

world exports {
  import stdio;

  export wasi:cli/environment@0.2.3;
  export wasi:cli/exit@0.2.3;
  export wasi:cli/stdin@0.2.3;
  export wasi:cli/stdout@0.2.3;
  export wasi:cli/stderr@0.2.3;
  export wasi:cli/terminal-input@0.2.3;
  export wasi:cli/terminal-output@0.2.3;
  export wasi:cli/terminal-stdin@0.2.3;
  export wasi:cli/terminal-stdout@0.2.3;
  export wasi:cli/terminal-stderr@0.2.3;

  export wasi:clocks/monotonic-clock@0.2.3;
  export wasi:clocks/wall-clock@0.2.3;

  export wasi:filesystem/preopens@0.2.3;
  export wasi:filesystem/types@0.2.3;

  export wasi:io/error@0.2.3;
  export wasi:io/poll@0.2.3;
  export wasi:io/streams@0.2.3;

  export wasi:random/insecure-seed@0.2.3;
  export wasi:random/insecure@0.2.3;
  // FIXME: wasi:random/random should specifically NOT be supported
  export wasi:random/random@0.2.3;
}
