package wasi-sandboxed:random@0.2.3;

world exports {
  export wasi:random/insecure-seed@0.2.3;
  export wasi:random/insecure@0.2.3;
  // FIXME: wasi:random/random should specifically NOT be supported
  export wasi:random/random@0.2.3;
}
