package wasi-sandboxed:sockets@0.2.6;

world exports {
  export wasi:sockets/instance-network@0.2.6;
  export wasi:sockets/network@0.2.6;
  export wasi:sockets/udp@0.2.6;
  export wasi:sockets/udp-create-socket@0.2.6;
  export wasi:sockets/tcp@0.2.6;
  export wasi:sockets/tcp-create-socket@0.2.6;
  export wasi:sockets/ip-name-lookup@0.2.6;
}
