package wasi-sandboxed:io@0.2.6;

interface stdio {
  write-stdout: func(contents: list<u8>);
  flush-stdout: func();

  write-stderr: func(contents: list<u8>);
  flush-stderr: func();
}

world exports {
  import stdio;
  export wasi:null/io@0.2.6;

  export wasi:io/error@0.2.6;
  export wasi:io/poll@0.2.6;
  export wasi:io/streams@0.2.6;
}
